// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnQT5e5N0Q4V1sPUqGZ09o0T-bNIjyxFQ',
    appId: '1:618956177661:web:773ea561ab0cb3b2dbbe94',
    messagingSenderId: '618956177661',
    projectId: 'wubrg-ee12a',
    authDomain: 'wubrg-ee12a.firebaseapp.com',
    databaseURL: 'https://wubrg-ee12a-default-rtdb.firebaseio.com',
    storageBucket: 'wubrg-ee12a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpBsqCQB883zmydFJdCjpADg19wl_6g6A',
    appId: '1:618956177661:android:221c4d99a83fdd96dbbe94',
    messagingSenderId: '618956177661',
    projectId: 'wubrg-ee12a',
    databaseURL: 'https://wubrg-ee12a-default-rtdb.firebaseio.com',
    storageBucket: 'wubrg-ee12a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHSUEDzVm1nY498VXDSgMqNsMYpti8tzU',
    appId: '1:618956177661:ios:123490125125ae7bdbbe94',
    messagingSenderId: '618956177661',
    projectId: 'wubrg-ee12a',
    databaseURL: 'https://wubrg-ee12a-default-rtdb.firebaseio.com',
    storageBucket: 'wubrg-ee12a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHSUEDzVm1nY498VXDSgMqNsMYpti8tzU',
    appId: '1:618956177661:ios:123490125125ae7bdbbe94',
    messagingSenderId: '618956177661',
    projectId: 'wubrg-ee12a',
    databaseURL: 'https://wubrg-ee12a-default-rtdb.firebaseio.com',
    storageBucket: 'wubrg-ee12a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnQT5e5N0Q4V1sPUqGZ09o0T-bNIjyxFQ',
    appId: '1:618956177661:web:fb7480baed1dc1b9dbbe94',
    messagingSenderId: '618956177661',
    projectId: 'wubrg-ee12a',
    authDomain: 'wubrg-ee12a.firebaseapp.com',
    databaseURL: 'https://wubrg-ee12a-default-rtdb.firebaseio.com',
    storageBucket: 'wubrg-ee12a.firebasestorage.app',
  );

}